# Generated by Django 4.2.20 on 2025-05-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=100)),
                ('experiencia_previa', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='miembros/')),
            ],
        ),
    ]
